version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"

  web:
    build: .
    command: symfony server:start
    volumes:
      - .:/var/www
    environment:
      DATABASE_URL: $DOCKER_DB_URL
      MAILER_URL: $MAILER_URL
    depends_on:
      - db
    links:
      - mailcatcher

  mailcatcher:
    image: schickling/mailcatcher:latest
    environment:
      - SMTP_IP=0.0.0.0
      - SMTP_PORT=1025
    ports:
      - 1080:1080
      - 1025:1025

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - web
    ports:
      - "80:80"
